### ISSUE TITLE
device/request API returns metrics with no value in response

### ISSUE THREAD

**Issue by LucaDazi** [eclipse-kapua/kapua#2731] opened 2019-10-04 15:26 UTC
When executing a devices/{deviceId}/request, and putting in Kura only response.code in the response message, Kapua includes generic exception metrics in the response, without a value, as per the following example:
```
{
  "capturedOn": "2019-10-04T15:14:42.43Z",
  "channel": {
    "appName": "APP",
    "version": "V1"
  },
  "payload": {
    "metrics": [
      {
        "valueType": "string",
        "name": "kapua.response.exception.stack"
      },
      {
        "valueType": "string",
        "name": "kapua.response.exception.message"
      },
      {
        "valueType": "string",
        "value": "200",
        "name": "response.code"
      }
    ]
  },
  "receivedOn": "2019-10-04T15:14:42.605Z",
  "scopeId": "AawzO-sihng",
  "sentOn": "2019-10-04T15:14:42.43Z"
}
```

1. Execute a devices/request API on a connected Kura device
2. Put only response.code=200 in the response metrics
3. See error

**Expected behavior**
Only metrics included in the response payload should be returned in the response.

**Version of Kapua**
version 1.0.6

**Type of deployment**
[ ] Local Vagrant deployment
[ ] Docker
[X] Openshift (in its variants) 
[ ] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[X] REST API
[ ] Message Broker
[ ] - Others

**Comment by Coduz** [comment] 2021-03-22 15:58
Closing this since is not reproducible

**Closed as completed by Coduz** 2021-03-22 15:58 UTC
Labels: Bug
