### ISSUE TITLE
How to create services via the REST API

### ISSUE THREAD

**Issue by megla-tlanghorst** [eclipse-kapua/kapua#3077] opened 2020-09-21 12:32 UTC
I'm trying to create a Group of services (CloudService, DataService, MqttDataTransport) for kura via the REST API. I'm trying to use `/{scopeId}/devices/{deviceId}/configurations`, but it only seems to configure existing services and doesn't create new ones. Is there any way to create those via the API?

**Comment by lorthirk** [comment] 2020-09-25 08:32
Hi @megla-tlanghorst,

`/{scopeId}/devices/{deviceId}/configurations` only exposes configurations for services already installed on Kura. In order to create a new service you have to create a new development package on Kura itself.

**Comment by megla-tlanghorst** [comment] 2020-09-25 08:35
So there's no way to create a new service via the kapua REST API, e.g. without direct access to the device? (The package for the service is already available, we already have 2 Services configured and I able to add a 3rd via the kura UI, but as the devices are out in the field and the UI also doesn't use the API it's hard to automate)

**Comment by lorthirk** [comment] 2020-09-25 08:40
Sorry, I partially misunderstood your question. Basically you're asking to create new instances of an already existing service via its factory.

As far as I know, the Kura API does not allow this. So I'm afraid there's no way currently. Have you already tried passing an array of instances to the `/configurations` endpoint in Kapua?

**Comment by megla-tlanghorst** [comment] 2020-09-25 08:43
Yes I have. To be sure I also loaded one of the current sets only modified the names and references but it still did seem to create anything.

**Comment by lorthirk** [comment] 2020-09-25 08:48
So I'm afraid the issue is more on the Kura API.

I'll close this for now, but should you find some new elements in Kura I'll gladly reopen this.

**Closed as completed by lorthirk** 2020-09-25 08:48 UTC
Labels: Question/support

**Comment by megla-tlanghorst** [comment] 2020-09-28 07:50
So apparently this works via snapshots, which are uploadable via the UI, but not via the API, so eventhough that probably won't help me here this might be worth an addition
