### ISSUE TITLE
Bug while connecting Kapua broker to MariaDB

### ISSUE THREAD

**Issue by GuillaumeBrgn** [eclipse-kapua/kapua#2701] opened 2019-09-12 15:10 UTC
We are trying to connect Kapua to MariaDB.

First we have copied the MariaDB driver into the broker container, then we put the environnement variables for ACTIVEMQ_OPTS like this : 
-Dcommons.db.connection.scheme=jdbc:mariadb 
-Dcommons.db.schema.update=true 
-Dcommons.db.jdbcConnectionUrlResolver=MariaDB 
-Dcommons.db.jdbc.driver=com.mariadb.jdbc.Driver 
-Dcommons.db.username="kapua" 
-Dcommons.db.password="mdpkapua" 
-Dcommons.db.schema=kapuadb 

When the container starts and try to create the tables, it display the following error :

```
Caused by: java.lang.RuntimeException: liquibase.exception.MigrationFailedException: Migration failed for change set KapuaDB/changelog-authorization-0.2.0.xml::changelog-authorization-domain-0.2.0::eurotech: Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE kapuadb.athz_domain (scope_id BIGINT(21) unsigned, id BIGINT(21) unsigned GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_on timestamp DEFAULT ${now} NOT NULL, created_by BIGINT(21) unsigned NOT NULL, name VARCHAR(255) NOT NULL, serviceName VARCHAR(1023) NOT NULL, CONSTRAINT PK_ATHZ_DOMAIN PRIMARY KEY (id), UNIQUE (name)): unknown escape sequence {now} 
  at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.update(KapuaLiquibaseClient.java:72) 
  at org.eclipse.kapua.broker.core.KapuaDatabaseCheckUpdate.<init>(KapuaDatabaseCheckUpdate.java:42) ... 35 more 
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set KapuaDB/changelog-authorization-0.2.0.xml::changelog-authorization-domain-0.2.0::eurotech: Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE kapuadb.athz_domain (scope_id BIGINT(21) unsigned, id BIGINT(21) unsigned GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_on timestamp DEFAULT ${now} NOT NULL, created_by BIGINT(21) unsigned NOT NULL, name VARCHAR(255) NOT NULL, serviceName VARCHAR(1023) NOT NULL, CONSTRAINT PK_ATHZ_DOMAIN PRIMARY KEY (id), UNIQUE (name)): unknown escape sequence {now} 
  at liquibase.changelog.ChangeSet.execute(ChangeSet.java:376) 
  at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:40) 
  at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:63) 
  at liquibase.Liquibase.update(Liquibase.java:136) 
  at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.executeMasters(KapuaLiquibaseClient.java:136) 
  at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.loadResourcesStatic(KapuaLiquibaseClient.java:108) 
  at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.update(KapuaLiquibaseClient.java:67) ... 36 more 
Caused by: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE kapuadb.athz_domain (scope_id BIGINT(21) unsigned, id BIGINT(21) unsigned GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_on timestamp DEFAULT ${now} NOT NULL, created_by BIGINT(21) unsigned NOT NULL, name VARCHAR(255) NOT NULL, serviceName VARCHAR(1023) NOT NULL, CONSTRAINT PK_ATHZ_DOMAIN PRIMARY KEY (id), UNIQUE (name)): unknown escape sequence {now} 
  at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:56) 
  at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:98) 
  at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1491) 
  at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1474) 
  at liquibase.changelog.ChangeSet.execute(ChangeSet.java:343) ... 42 more
```

In order to fix this problem, we tried to modify all the XML files which use the variable, replacing the variable ${now} by NOW(), but we still have the same issue.

Is there any documentation which explain how to do this ?

**Comment by lorthirk** [comment] 2019-09-12 15:38
The `${now}` notation is a Liquibase abstraction to use the proper function when running the migrations, so I need to investigate a bit what's going on.

What version of Kapua are you running, and how do you deploy it?

**Comment by mderbal** [comment] 2019-09-13 10:14
Hello lorthirk,

I'm working with Guillaume Bourgoin and that's why I answer in his place.

We used the version 1.0.6 of kapua , we add driver for mariadb in the docker image's before sending it to openshift.

we have also a mariadb container on openshift named db and exposed on port 3306 , we have created the database kapuadb on it with the grant privileges.

**Comment by Coduz** [comment] 2019-09-13 10:33
Hi all, 

The configuration of the parameters seems correct, matches the configuration that we use to test MariaDB compatibility. 
If the Driver is correctly configured, everything should work.

The problem I can see is that Liquibase is not replacing `${now}` properties in `.xml` schema definition files. This property should be resolved by looking at the `common-properties.xml` file, which according to the database selected replaces the value with the specific function that fetches the CurrentTime. 

Could you please check on the container the `tmp` directory? It should contain all available Liquibase definition files and post the content on all directories?

Regards, 

_Alberto_

**Comment by mderbal** [comment] 2019-09-13 12:18
I tried to connect to terminal before the container end in error.
Please see the attached files for a screenshot of the contents of tmp directory

**Comment by mderbal** [comment] 2019-09-13 12:21
![Screenshot_2019-09-13 OpenShift Web Console](https://user-images.githubusercontent.com/45426153/64861992-b92d3500-d631-11e9-9c34-f4e263deae50.png)

**Comment by Coduz** [comment] 2019-09-13 13:08
Hi @mderbal ,

You can run the container with the `/bin/bash` to start the container and make it not die when the broker goes on error.

From there, you have to check the execution logs of the broker to find where it is the `tmp` directory of the broker (sorry I didn't mentioned that was the `tmp` of the broker), in which all liquibase files are copied before executing them.

By doing the `ls -lR` in that directory we can check that all files have been copied correctly.

Regards, 

_Alberto_

**Comment by mderbal** [comment] 2019-09-13 13:18
![capturetmp](https://user-images.githubusercontent.com/45426153/64865505-b5051580-d639-11e9-8d77-16c8b30afd64.png)

**Comment by mderbal** [comment] 2019-09-13 13:21
I see that the directory you want was not /tmp but /opt/activemq/tmp and it contains the .xml used by liquibase to create the tables.

**Comment by mderbal** [comment] 2019-09-16 08:36
Hi,

No news for our issue , can you please help us ?

Regards

**Comment by Coduz** [comment] 2019-09-16 09:01
Hi @GuillaumeBrgn , 

Is that all of the content of the container?
It seems interrupted in the execution!

_Alberto_

**Comment by mderbal** [comment] 2019-09-16 09:37
Hi

Yes it's all the contents , the interruption came after the prompt $ like you can see

**Comment by Coduz** [comment] 2019-09-16 10:27
That seems a lot strange because the list should be a lot longer. As you can see there are only scripts for the 0.2.0 release. You should find also some in a folder called 1.0.0.

Are those container that you built on your own, right?

**Comment by mderbal** [comment] 2019-09-16 12:36
Hi,

Yes and I show another folder 1.0.0 is not present on my container

**Comment by Coduz** [comment] 2019-09-16 12:39
Uhmm it seems that for some reasons the container has not being built correctly then. 

What command you used to build? 
Which is the starting TAG?
What changes you made?

**Comment by mderbal** [comment] 2019-09-16 14:04
The tag is 1.0.6 and the changes we do : 
- adding jars driver MySQL and MariaDB in the container by using docker build command with ADD command in DockerFile.
- replacing in xml files ${now} by NOW()

**Comment by Coduz** [comment] 2019-09-17 09:05
You have published your branch? 
I would like to checkout the code and try. 
It would be much easier to investigate the problem!

**Comment by mderbal** [comment] 2019-09-18 13:45
No I don't have published my branch , it's the same code than published on GitHub on branch develop.

Just added the drivers mariadb-java-client-2.4.3.jar,mysql-connector-java-8.0.17.jar and mysql.jar and replaced  in xml files liquibase ${now} by NOW()

**Comment by Coduz** [comment] 2019-09-23 08:34
Hi @mderbal ,

could you please publish your changes? I would like to debug the changes and check where the problem is.

Thanks, 

_Alberto_

**Comment by mderbal** [comment] 2019-09-23 14:15
Hi @Coduz,

For mariadb you can take the latest version of docker container and for events-broker the tag 1.0.6.
For the broker who makes the issue , you can download the container image archive in the link below :
https://we.tl/t-BzZdixhO9r 

Regards

Momo

**Comment by Coduz** [comment] 2019-09-23 15:41
I've tried to download the exported container.
It starts but it is dying with no output, so I cannot help you with this.

**Comment by Coduz** [comment] 2019-09-26 15:50
HI @mderbal ,

Do you still need help? 

Regards,

_Alberto_

**Comment by Coduz** [comment] 2019-09-30 09:30
Hi @mderbal ,

I'm closing this. 
Feel free to reopen this if you need more help.

Regards, 

_Alberto_

**Closed as completed by Coduz** 2019-09-30 09:30 UTC
Labels: Question/support
