### ISSUE TITLE
"NULL" Errors When Trying to List Roles and Permissions in User View

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse-kapua/kapua#2839] opened 2020-01-30 07:31 UTC
When trying to list roles and permissions of a user, you get a "null" error without a description (see screenshot bellow).

**Testflow:**
1. Checkout latest develop branch, build it with the "mvn clean install -DskipTests -Pconsole,docker" command
2. Open kapua on local machine in web browser on "localhost:8080"
3. Login as kapua-sys user
4. Go to Users, select kapua-broker/kapua-sys users and navigate to "Roles" and/or "Permission" tabs
5. Observe the "null" error.

**Expected behavior**
No error should be shown if user with ALL:ALL:ALL permissions try to view roles or permissions.

**Screenshot:**
<img width="1178" alt="Screenshot 2020-01-30 at 08 25 37" src="https://user-images.githubusercontent.com/15121999/73429012-df324800-433a-11ea-9790-8c6b8abacf7e.png">

**Version of Kapua**
1.1.0 - SNAPSHOT; Develop branch

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

**Comment by Coduz** [comment] 2020-02-10 11:24
Hi @LeoNerdoG ,

I'm assuming the session was the same of the issue #2838 .

Could you please try that solution and check again this behaviour? 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment] 2020-02-11 11:09
Hey @Coduz,
I have checked this in the latest develop branch with all the caches deleted, but the problem persists. I tried this on Firefox, Chrome, Safari and Opera and it is all the same in all of the browsers.

**Comment by lorthirk** [comment] 2020-03-24 10:19
#2910 is a duplicate of this one. However, I'll close this as duplicate, as #2910 covers also Roles Permissions.

**Comment by lorthirk** [comment] 2020-03-24 10:23
As noted in #2910, the same issue occurs also in Role -> Permissions.

**Closed as completed** 2020-03-24 11:51 UTC
Labels: Bug, Console GWT
